# Generated by Django 2.1.7 on 2019-04-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_list',
            name='Plot',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='Poster',
            field=models.CharField(max_length=5000),
        ),
    ]
